#ifndef MAINCODE_CONFIGDEFAULTS_H
#define MAINCODE_CONFIGDEFAULTS_H

#define MAINCONFIG_NUM_LEDS 300
#define MAINCONFIG_MAX_BRIGHTNESS 150
#define MAINCONFIG_CURRENT_BRIGHTNESS 100
#define MAINCONFIG_LAST_ID "1"
#define MAINCONFIG_IS_SOLID_COLOR false
#define MAINCONFIG_IS_SEGMENTED_COLOR false
#define MAINCONFIG_COLOR 0xffffff
#define MAINCONFIG_SEGMENTED_PRESET_ID "NULL"
#define WIFI_SSID "Nakotech_LED_Strip"
#define WIFI_PASS "12345678"

#endif //MAINCODE_CONFIGDEFAULTS_H
